//
//  MoviesJSON.swift
//  MoviesAPI
//
//  Created by Tekla on 11/18/23.
//

import Foundation
let movies = """
{"Title":"Big Hero 6","Year":"2014","Rated":"PG","Released":"07 Nov 2014","Runtime":"102 min","Genre":"Animation, Action, Adventure","Director":"Don Hall, Chris Williams","Writer":"Jordan Roberts, Robert L. Baird, Daniel Gerson","Actors":"Ryan Potter,  Scott Adsit, Jamie Chung","Plot":"A special bond develops between plus-sized inflatable robot Baymax and prodigy Hiro Hamada, who together team up with a group of friends to form a band of high-tech heroes.","Language":"English","Country":"United States, Japan","Awards":"Won 1 Oscar. 17 wins & 58 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BMDliOTIzNmUtOTllOC00NDU3LWFiNjYtMGM0NDc1YTMxNjYxXkEyXkFqcGdeQXVyNTM3NzExMDQ@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.8/10"},{"Source":"Rotten Tomatoes","Value":"90%"},{"Source":"Metacritic","Value":"74/100"}],"Metascore":"74","imdbRating":"7.8","imdbVotes":"488,546","imdbID":"tt2245084","Type":"movie","DVD":"22 Nov 2015","BoxOffice":"$222,527,828","Production":"N/A","Website":"N/A","Response":"True",
"Title":"Howl's Moving Castle","Year":"2004","Rated":"PG","Released":"17 Jun 2005","Runtime":"119 min","Genre":"Animation, Adventure, Family","Director":"Hayao Miyazaki","Writer":"Hayao Miyazaki, Diana Wynne Jones","Actors":"Chieko Baishô, Takuya Kimura, Tatsuya Gashûin","Plot":"When an unconfident young woman is cursed with an old body by a spiteful witch, her only chance of breaking the spell lies with a self-indulgent yet insecure young wizard and his companions in his legged, walking castle.","Language":"Japanese","Country":"Japan","Awards":"Nominated for 1 Oscar. 14 wins & 20 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BNmM4YTFmMmItMGE3Yy00MmRkLTlmZGEtMzZlOTQzYjk3MzA2XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.2/10"},{"Source":"Rotten Tomatoes","Value":"87%"},{"Source":"Metacritic","Value":"82/100"}],"Metascore":"82","imdbRating":"8.2","imdbVotes":"428,728","imdbID":"tt0347149","Type":"movie","DVD":"15 Dec 2019","BoxOffice":"$6,789,268","Production":"N/A","Website":"N/A","Response":"True",
    "Title":"Kung Fu Panda","Year":"2008","Rated":"PG","Released":"06 Jun 2008","Runtime":"92 min","Genre":"Animation, Action, Adventure","Director":"Mark Osborne, John Stevenson","Writer":"Jonathan Aibel, Glenn Berger, Ethan Reiff","Actors":"Jack Black, Ian McShane, Angelina Jolie","Plot":"To everyone's surprise, including his own, Po, an overweight, clumsy panda, is chosen as protector of the Valley of Peace. His suitability will soon be tested as the valley's arch-enemy is on his way.","Language":"English","Country":"United States, United Kingdom","Awards":"Nominated for 1 Oscar. 15 wins & 39 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BODJkZTZhMWItMDI3Yy00ZWZlLTk4NjQtOTI1ZjU5NjBjZTVjXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.6/10"},{"Source":"Rotten Tomatoes","Value":"87%"},{"Source":"Metacritic","Value":"74/100"}],"Metascore":"74","imdbRating":"7.6","imdbVotes":"502,044","imdbID":"tt0441773","Type":"movie","DVD":"25 Nov 2015","BoxOffice":"$215,771,591","Production":"N/A","Website":"N/A","Response":"True",
    "Title":"The Mitchells vs the Machines","Year":"2021","Rated":"PG","Released":"30 Apr 2021","Runtime":"114 min","Genre":"Animation, Action, Adventure","Director":"Michael Rianda, Jeff Rowe","Writer":"Michael Rianda, Jeff Rowe, Peter Szilagyi","Actors":"Abbi Jacobson, Danny McBride, Maya Rudolph","Plot":"A quirky, dysfunctional family's road trip is upended when they find themselves in the middle of the robot apocalypse and suddenly become humanity's unlikeliest last hope.","Language":"English","Country":"United States, Hong Kong","Awards":"Nominated for 1 Oscar. 46 wins & 64 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BMjdkZjNjNDItYzc4MC00NTkxLTk1MWEtY2UyZjY5MjUwNDNkXkEyXkFqcGdeQXVyMTA1OTcyNDQ4._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.6/10"},{"Source":"Rotten Tomatoes","Value":"97%"},{"Source":"Metacritic","Value":"81/100"}],"Metascore":"81","imdbRating":"7.6","imdbVotes":"121,318","imdbID":"tt7979580","Type":"movie","DVD":"30 Apr 2021","BoxOffice":"N/A","Production":"N/A","Website":"N/A","Response":"True",
    "Title":"Brave","Year":"2012","Rated":"PG","Released":"19 Jun 2012","Runtime":"93 min","Genre":"Animation, Action, Adventure","Director":"Mark Andrews, Brenda Chapman, Steve Purcell","Writer":"Brenda Chapman, Mark Andrews, Steve Purcell","Actors":"Kelly Macdonald, Billy Connolly, Emma Thompson","Plot":"Determined to make her own path in life, Princess Merida defies a custom that brings chaos to her kingdom. Granted one wish, Merida must rely on her bravery and her archery skills to undo a beastly curse.","Language":"English","Country":"United States, Japan","Awards":"Won 1 Oscar. 20 wins & 48 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BMzgwODk3ODA1NF5BMl5BanBnXkFtZTcwNjU3NjQ0Nw@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"7.1/10"},{"Source":"Rotten Tomatoes","Value":"79%"},{"Source":"Metacritic","Value":"69/100"}],"Metascore":"69","imdbRating":"7.1","imdbVotes":"431,674","imdbID":"tt1217209","Type":"movie","DVD":"01 Jun 2014","BoxOffice":"$237,283,207","Production":"N/A","Website":"N/A","Response":"True",
   "Title":"How to Train Your Dragon","Year":"2010","Rated":"PG","Released":"26 Mar 2010","Runtime":"98 min","Genre":"Animation, Action, Adventure","Director":"Dean DeBlois, Chris Sanders","Writer":"William Davies, Dean DeBlois, Chris Sanders","Actors":"Jay Baruchel, Gerard Butler, Christopher Mintz-Plasse","Plot":"A hapless young Viking who aspires to hunt dragons becomes the unlikely friend of a young dragon himself, and learns there may be more to the creatures than he assumed.","Language":"English","Country":"United States, France","Awards":"Nominated for 2 Oscars. 25 wins & 63 nominations total","Poster":"https://m.media-amazon.com/images/M/MV5BMjA5NDQyMjc2NF5BMl5BanBnXkFtZTcwMjg5ODcyMw@@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.1/10"},{"Source":"Rotten Tomatoes","Value":"99%"},{"Source":"Metacritic","Value":"75/100"}],"Metascore":"75","imdbRating":"8.1","imdbVotes":"780,119","imdbID":"tt0892769","Type":"movie","DVD":"25 Nov 2015","BoxOffice":"$217,581,231","Production":"N/A","Website":"N/A","Response":"True",
   ""Request" : "?t=Spider-Man%3A+Across+the+Spider-Verse",Title":"Spider-Man: Across the Spider-Verse","Year":"2023","Rated":"PG","Released":"02 Jun 2023","Runtime":"140 min","Genre":"Animation, Action, Adventure","Director":"Joaquim Dos Santos, Kemp Powers, Justin K. Thompson","Writer":"Phil Lord, Christopher Miller, Dave Callaham","Actors":"Shameik Moore, Hailee Steinfeld, Brian Tyree Henry","Plot":"Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. When the heroes clash on how to handle a new threat, Miles must redefine what it means to be a ...","Language":"English","Country":"United States","Awards":"5 wins & 3 nominations","Poster":"https://m.media-amazon.com/images/M/MV5BMzI0NmVkMjEtYmY4MS00ZDMxLTlkZmEtMzU4MDQxYTMzMjU2XkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.7/10"},{"Source":"Rotten Tomatoes","Value":"96%"},{"Source":"Metacritic","Value":"86/100"}],"Metascore":"86","imdbRating":"8.7","imdbVotes":"290,497","imdbID":"tt9362722","Type":"movie","DVD":"08 Aug 2023","BoxOffice":"$381,311,319","Production":"N/A","Website":"N/A","Response":"True"
}
"""
